---
useTabs: false
singleQuote: false
trailingComma: "none"
semi: true
tabWidth: 4
printWidth: 100
endOfLine: "lf"
plugins:
    - prettier-plugin-svelte
overrides:
    - files: "*.svelte"
      options:
          parser: svelte
